### PR TITLE
tuning for real time processing(150~250% better performance)

### PR DESCRIPTION
**Pull request by Kanasansoft**
I did tuning for real time processing.
(example : use with WebRTC)

about 150~250% better performance.

demo
http://www.kanasansoft.com/Kanasansoft/computer_vision_for_real_time_processing/computer_vision_for_real_time_processing.html

### CODE REVIEW

**Comment by liuliu** [comment]
Thanks! I will take a look this weekend and merge it.

**Comment by Kanasansoft** [comment]
p.s.
The parallable function use Web Workers.
First postMessage is error because of Web Workers can not send (msg contain) CanvasPixelArray.
JSON.stringify run before second postMessage.
JSON.stringify is slowly for big data.
And JSON.parse run in worker thread.
JSON.parse is slowly for big data, too.

in my mathine
JSON.stringify : over 2000ms
JSON.parse : about 1500ms

**Comment by liuliu** [comment]
Google Chrome does a terrible job in doing this. It can pass around JSON object, but it does JSON serialization internally. Firefox gets this right and passes JSON object directly. That is why parallable works OK in Firefox. Of course, I checked the Web Worker spec about 1 and half years ago, there is a great chance that I am outdated :)

**Comment by Kanasansoft** [comment]
I see.

**Comment by liuliu** [comment]
Thanks, I will do a manual merge for ccv.js, but not ccv_in_realtime.js. I intended to make ccv.js truly work with web worker :-)

**Pull request closed without merging**
