### PR TITLE
Change build system to CMake

### PR DESCRIPTION
**Pull request by rjw57**
Hi there. This pull request is to add CMake as a build system. The custom Makefile solution is workable but CMake adds the ability to auto-detect a number of the libraries that one has to manually specify via ./configure at the moment. Similarly it contains logic to automatically handle the C dependencies. Lastly it allows for out-of-tree builds which I find terribly convenient when building for different systems.

I have ported the test system over to CTest which allows all tests to be run via a 'make test' target or a subset matching a regex via 'ctest -R [regex]'. Run 'ctest -V' to see output from the tests.

A couple of the commits here also change some #include statements to match the directories which CMake finds for us rather than hard-coded paths.

If this is of interest, I can add in checks for SSE2, -ffast-math and liblinear but I didn't want to spend too much time on this if the concept of using CMake does not interest you.

### CODE REVIEW

**Comment by c00kiemon5ter** [comment]
CMake requires C++ to be bootstrapped and imo that is overkill.
Additionally, I dont consider cmake files any more readable or simpler. 
I would say no, but it is not my choice, and I just started watching this project, so feel free to ignore me.

**Comment by rjw57** [comment]
In the sense that CMake requires C++ to be compiled itself, yes. But I suspect it would be hard to get any system compiled without a C++ compiler. If you install CMake from binary, you don't need a C++ compiler and I've explicitly made sure that this CMake build system marks the project as being only C.

The existing makefile-based build system also favours clang which is both a C and C++ compiler.

I recognise that build systems are a matter of personal taste, however, and so the decision of the maintainer is ultimately 'correct' since they have to maintain it.

**Comment by liuliu** [comment]
Thanks, this is great. This project indeed needs a "build system". But here is my take:

ccv is aiming at being drop-in statically-linked library, there are several appealing aspects of cmake to compensate that, such as it can emit a Visual Studio or XCode project directly. In this way, you can drag-n-drop the generated project file into your own project, and boom, done.

However, I also want ccv to be explicit, in that retrospective, cmake is the dark magic. Once your project is tied to cmake, it requires: a cmake binary to start with, and, it also hard to separate it from cmake. The first one is somewhat endurable (better than waf!), but the second one is not acceptable. Look at OpenCV, nowadays, it is really really hard to build its component without cmake, for many internal usages (etc. large scale server deployment) that uses custom build system for dependency/OS version management, it becomes a huge labor just to get that monster build.

I am still looking for an ideal build system, it should have:

1). no binary required, no other dependencies. It can be a generated script (automake/autoconf, God, smells), but the generated one is still highly readable, and easy to tear down;
2). automatic dependency detection, but explicit about what can/cannot and how;
3). pretty output with color/underscore/bold format;

**Comment by rjw57** [comment]
A fair comment. I wish you luck finding that build system though! CMake manages 2) and 3) but fails 1) miserably. And as you point out, autoconf/automake is not know for generating readable output.

Closing the pull request as obviously CMake isn't a build system which satisfies your criteria. Thanks for the review though.

**Pull request closed without merging**
