### PR TITLE
SWT speed up...

### PR DESCRIPTION
**Pull request by mledford**
I removed a subtract and a multiply from calculating the memory location by using a pre-calculated lookup table. When testing I found this decreased the processing time of up to 35%.

### CODE REVIEW

**Comment by mledford** [comment]
I have found some bugs in the implementation. I am looking to see if it's something that can be corrected.

**Comment by mledford** [comment]
I made some bad assumptions about the algorithm and so most everything in this pull request is invalid. The speed ups I saw were due to short circuiting the algorithm. One of the commits should still be valid where I reordered the memory accesses but is rather small on whole.

**Comment by mledford** [comment]
After my embarrassing last try I looked at it again and managed to improve performance while faithfully maintaining the algorithm's integrity. Hopefully I got it right this time. I have reopened the pull request and hopefully the new commits will show up.

Basically there are two tight loops in ccv_swt() that do memory location calculations. It so happens that these loops can be modified in such a way that part of the memory location can be pre-calculated and then use a lookup table with some simple addition to gain some speed.

**Comment by asinteg-daehn** [comment]
+1

**Pull request closed without merging**
