### PR TITLE
Build system improvements and video reading fix for bin/tld.c

### PR DESCRIPTION
**Pull request by smvv**
This build system will enable parallelized builds and tracks changes in header files properly. Changing an header file will result in a rebuild of the library and/or binaries.

The first commit fixes the video reading part of bin/tld.c. Due to incorrect usage of the libav API, it was not possible for me to use the demo. Symptoms were complaining about incorrect nalsizes and not flipping "got_picture" to true. The first commit should resolve that issue.

### CODE REVIEW

**Comment by liuliu** [comment]
This looks good, I will do a manual merge tonight. BTW, do you know if this builds runs with clang's static analyzer now? I am trying to get it running on the old build sys, but has no luck.

**Comment by smvv** [comment]
Please include these two commits as well: eb1337685c621186a6913b4a066b737361493e0e and 33e1c6583a6153535af05daaad4cf0209810c189. Without the first patch, the build system does not look on the right location for the libccv.a file. The second commit is just some code cleanup.

Is there a specific reason why you do not have -Wextra and -fPIC in CFLAGS? Using -fPIC allows us to create shared libraries, instead of compiling static builds. Currently, the size of each binary in bin/ is >2.0mb, which is rather large.

I tried "scan-build make" but it says "scan-build: Removing directory '/tmp/scan-build-2012-11-13-1' because it contains no reports.". Did you have a similar error? It tried it with clang 2.9.

If you have any questions about the new build system, feel free to ask of course.

**Comment by liuliu** [comment]
I don't think that this diff does the right thing.

It invokes cc (alias to gcc) to compile, rather than the designated clang compiler, there are redundant rules that I cannot figure out why is not called. The ./configure shell-script doesn't read old config.mk and skip properly. Trying to fix these issues now.

**Comment by liuliu** [comment]
Need to spend more time to improve my GNU make skill, before that, there are a few issues in this diff makes me uncomfortable to merge yet (the main makefile's %.o: %.c rule never get called, a few %.o: %c rules in suffix.mk is executed, no libccv.a object get emitted, maybe a make version problem?: GNU Make 3.81)

Also, the ffmpeg part is tricky too, it cannot now execute on my mpg file. Note that my tld.c is known to have memory issues and such, I need to fix these, meanwhile, the tld implementation itself is separately tested with valgrind to make sure no memory leak in the implementation.

Thanks for the diff, I just need more time to make sure everything I understands ;-( a night is just not enough.

**Comment by liuliu** [comment]
also, to answer the question about why not a shared object, because ccv uses some global data, and it would be troublesome to make it a shared object. Personally, for any serious project, ccv should be just included in the project and use link-time-optimization to remove all these unused code if you care about binary size.

**Comment by smvv** [comment]
I fixed the issue with libccv.a and integrated test/ in the new central build system. Both "make test" as well as "make" work as expected.

I also ran make through clang's static analyser (use "scan-build make STATIC_ANALYZER=1") and it produced an error report. Make sure that you first remove /config.mk and generate it again using "./configure". Otherwise, config.mk will not have the proper content.

There is a null pointer dereference issue in lib/ccv_swt.c on line 730:

730:    for (i = 0; i < all_words->rnum; i++)

where all_words is null. There are a couple of checks above involving scale_invariant and when scale_invariant is false, all_words is set. However, when scale_invariant is true, all_words remains null and that will cause a null pointer dereference on line 730. See clang's static analyser report (use "scan-view /tmp/scan-build-2012-11-14-1" or a similar path) for more details.

**Comment by liuliu** [comment]
thanks for the pointer, I am running trunk version of scan-build with clang now, quite a few warnings, no surprisingly.

**Pull request closed without merging**
