### PR TITLE
Altered the build system to better accommodate building on Mac OS X.

### PR DESCRIPTION
**Pull request by mledford**
Checks to see if Xcode command line tools are installed and if not uses xcrun to run relevant commands. Gives indication which Xcode package is selected using xcode-select. Asks which SDK should be used to build against. Asks which architecture should be used to build.

### CODE REVIEW

**Comment by koudelka** [comment]
thanks! :+1:

**Comment by liuliu** [comment]
manually merged into unstable. Thanks. However, I do get clang warning about unused -arch x86_64, quick search doesn't show me how to properly get over this warning. (I can do -Qunused-argument, but it seems quite bad).

**Comment by mledford** [comment]
Strange I don't get any warnings. I'm using the following tools:

Xcode 4.5.2 (4G2008a)
Apple clang version 4.1 (tags/Apple/clang-421.11.66) (based on LLVM 3.1svn)

Is the warning coming from Apple build tools or from another toolchain? Could it be an older version?

That said I considered introducing the default arch only if the build system was Mac OS X but I thought there might be others who might possibly want to change that setting and so I placed there it for everyone.

**Comment by liuliu** [comment]
I am using clang version 3.3 (trunk 168355), which is the bleeding-edge one. I think that clang on other platforms just doesn't support -arch or something else that I don't understand yet.

**Comment by mledford** [comment]
OK. I did some searching and found the following thread on the clang front end developers' list from a few years ago.

http://lists.cs.uiuc.edu/pipermail/cfe-dev/2010-July/009873.html

It appears that -arch is currently only supported on Darwin at the moment because it is fully supported throughout the toolchain. So it appears I should have used the default arch only if the build system is Mac OS X. I will fix this up and send another pull request. Thanks for letting me know there was a problem!

**Pull request closed without merging**
