### PR TITLE
Update js/ccv.js

### PR DESCRIPTION
**Pull request by halldb02**
introduces bitwise operators for multiplication and division by factors of 2
caches loop limit lookups
caches object lookups

### CODE REVIEW

**Comment by liuliu** [comment]
Do you have perf figures for this diff to back it up? Thanks!

**Comment by liuliu** [comment]
I cannot test this out in Firefox or Chrome, could you try to fix all the js errors? thanks!

**Comment by dennishall** [comment]
Please ignore this one.

**Comment by liuliu** [comment]
Thanks, but I will merge Kanasansoft's patch first.

**Pull request closed without merging**
