### PR TITLE
Unstable win32

### PR DESCRIPTION
**Pull request by Corion**
These are my changes to make siftmatch.exe build on Windows mingw gcc 4.4.1.

These changes are ugly, especially the make.bat things I did. I plan to add a proper Makefile once I get the build somewhat stabilized.

### CODE REVIEW

**Comment by liuliu** [comment]
Hi, thanks for the pull request, I am more interested in the script that compiles with windows, can you elaborate on that? I have tried to fix the memory access error in sift, please checkout the my new commit (b3591e0062fd89514bae4bbe477a775c3d7bfb3f) and see if that fix the problem, thanks!

**Comment by Corion** [comment]
There are now new commits adding "makefile.mk" for bin/ and lib/ , which do build the library and programs using dmake.exe on Windows. There were very little changes needed, mostly in the files included.he two relevant patches are e4dce69 and 0472e6f I think.

**Comment by liuliu** [comment]
Sorry that recently I am pushing some aggressive changes in APIs and code structure in general that potentially could break this pull request. After I finished dpm and a few touches in bbf, there will finally be a tagged 0.1 version, could you modify this pull request by then? Thanks!

**Comment by Corion** [comment]
Hello,

Am 05.04.2012 01:39, schrieb Liu Liu:

> Sorry that recently I am pushing some aggressive changes in APIs and code structure in general that potentially could break this pull request. After I finished dpm and a few touches in bbf, there will finally be a tagged 0.1 version, could you modify this pull request by then? Thanks!

I've rebased my branch request onto your changes. I'll withdraw this 
pull request and send a fresh one for the rebased branch.

-max

**Comment by Corion** [comment]
OK - closing the pull request didn't work out, but I was able to update the commit range. This branch should (currently) merge without problems into your unstable branch. If you don't want to merge it now, I'll rebase again later - no need to hurry.

**Comment by liuliu** [comment]
Hi, since 0.1 is out, if you are still interested in this, could you patch stable/r0.1-rc1 branch with Win32 compilation support? That will be a great help!

**Comment by Corion** [comment]
Hello,

> Hi, since 0.1 is out, if you are still interested in this, could you
> patch stable/r0.1-rc1 branch with Win32 compilation support? That
> will be a great help!

Yes, I'm still interested! I'm just really busy currently, so I don't 
know if I can submit a patch-branch before end of this week. The main 
meat of my change is to guard against #include <malloca.h> on Win32 in 
lib/ccv.h:

+#ifndef _MSC_VER
  #include <unistd.h>
  #include <stdint.h>
+#endif
...
+#ifdef _WIN32
+#include <malloc.h>
+#else
  #include <alloca.h>
+#endif

But I need some time to do an actual diff between my git-tree for the 
Perl bindings at https://github.com/Corion/image-ccv/ (in the directory 
ccv-lib) and your source.

-max

**Comment by mhm0902** [comment]
在windows下运行，训练出来的分类器，读取有问题。
需要转换。

**Comment by bompus** [comment]
Any chance on getting these merged with a tutorial on how to compile on Win32? Ideally with Visual Studio (C++) 2012.

Thank you!

**Comment by Corion** [comment]
I just saw your request - sorry for not reacting sooner :-/

I don't use Visual Studio, so I can't be of help here, sorry. I only use the MinGW gcc compiler, and that only because it's included with Strawberry Perl.

**Pull request closed without merging**
